# Generated by Django 2.2.12 on 2022-03-03 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_event_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
