# Generated by Django 2.2.12 on 2022-03-02 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_desc', models.TextField()),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprroved')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
