# Generated by Django 2.2.12 on 2022-03-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='attendees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
